repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        name: Gitleaks
        entry: gitleaks detect
        language: system
        types: [text]
        exclude: ^.*\.(png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|pdf|zip|tar|gz|lock|log)$
        args: ["--no-banner", "--verbose"]
        stages: [pre-commit, pre-push]
